a=int(input("nhập một số nguyên bất kỳ cho a:"))
b=int(input("nhập một số nguyên bất kỳ cho b:"))
c=int(input("nhập một số nguyên bất kỳ cho c:"))
print("tổng của a, b và c là:", a+b+c)
print("tích của a, b và c là:", a*b*c)
print("giá trị trung bình là:", (a+b+c)/3)