t=float(input("nhập khối lượng (talent):"))
p=float(input("nhập khối lượng (pound):"))
l=float(input("nhập khối lượng (lot):"))
S=(((t*20+p)*32+l)*13.3)
kg=(S//1000)
g=(S%1000)
print("tổng khối lượng là: " ,kg ,"KG và", g ,"G")